// Auto-generated menu items for Ultimate Menu Builder
const i = (id, label, type = 'item', badge = null) => ({ id, label, type, badge });
const g = (id, label) => i(id, label, 'group', 'Group');
const h = (id, label) => i(id, label, 'header', 'Header');

export const ALL_ITEMS = [
  i('academic-dashboard','Academic Dashboard'),
  i('academic-sessions','Academic Sessions'),
  g('academics','Academics'),
  g('accounting','Accounting'),
  g('accounts','Accounts'),
  i('accounts-dashboard','Accounts Dashboard'),
  h('accounts-management','ACCOUNTS MANAGEMENT'),
  i('add-stock','Add Stock'),
  i('admission-enquiries','Admission Enquiries'),
  i('admission-form-fields','Admission Form Fields'),
  i('admission-settings','Admission Settings'),
  i('agent-logs','Agent Logs'),
  i('ai-chatbot','AI Chatbot'),
  i('all-devices','All Devices'),
  i('all-surveys','All Surveys'),
  i('all-transactions','All Transactions'),
  i('apply-leave','Apply Leave'),
  i('appraisal-criteria','Appraisal Criteria'),
  i('appraisal-cycles','Appraisal Cycles'),
  i('appraisals','Appraisals'),
  i('approve-leave','Approve Leave'),
  i('apps-center','Apps Center'),
  g('assessment','Assessment'),
  i('assessment-dashboard','Assessment Dashboard'),
  i('assessment-guide','Assessment Guide'),
  i('assessment-reports','Assessment Reports'),
  i('assessments','Assessments'),
  i('asset-assignments','Asset Assignments'),
  i('asset-audits','Asset Audits'),
  i('asset-categories','Asset Categories'),
  i('asset-dashboard','Asset Dashboard'),
  i('asset-depreciation','Asset Depreciation'),
  i('asset-disposals','Asset Disposals'),
  i('asset-maintenance','Asset Maintenance'),
  g('asset-management','Asset Management'),
  i('asset-register','Asset Register'),
  i('asset-reports','Asset Reports'),
  i('assign-class-teacher','Assign Class Teacher'),
  i('assign-electives','Assign Electives'),
  i('assign-fees','Assign Fees'),
  i('assign-subjects','Assign Subjects'),
  i('attendance-logs','Attendance Logs'),
  i('audit-trail','Audit Trail'),
  i('auto-send-settings','Auto-send Settings'),
  i('backup-management','Backup Management'),
  i('bank-accounts','Bank Accounts'),
  i('behavior-records','Behavior Records'),
  g('biometric-devices','Biometric Devices'),
  i('birthday-manager','Birthday Manager'),
  i('book-categories','Book Categories'),
  i('broadcast-history','Broadcast History'),
  i('browse-articles','Browse Articles'),
  i('camera-wall','Camera Wall'),
  i('campus-workers','Campus Workers'),
  i('card-appearance','Card Appearance'),
  i('card-designs','Card Designs'),
  g('cbc-academics','CBC Academics'),
  i('cbc-assessments','CBC Assessments'),
  i('cbc-dashboard','CBC Dashboard'),
  i('cbc-reports','CBC Reports'),
  i('cbse-disclosure','CBSE Disclosure'),
  g('cctv','CCTV'),
  i('cctv-access-log','CCTV Access Log'),
  i('cctv-cameras','CCTV Cameras'),
  i('certificate-templates','Certificate Templates'),
  g('certificates','Certificates'),
  i('certificates-documents','Certificates & Documents'),
  i('chapters-topics','Chapters & Topics'),
  i('chat-moderation','Chat Moderation'),
  i('class-timetable','Class Timetable'),
  i('classes','Classes'),
  i('classwork-logbook','Classwork & Logbook'),
  i('cocurricular-areas','Cocurricular Areas'),
  i('cocurricular-grades','Cocurricular Grades'),
  i('collect-fees','Collect Fees'),
  i('comms-wallet','Comms Wallet'),
  g('communicate','Communicate'),
  h('communication','COMMUNICATION'),
  h('communications','COMMUNICATIONS'),
  i('complaints','Complaints'),
  g('compliance-governance','Compliance & Governance'),
  i('compliance-calendar','Compliance Calendar'),
  i('compliance-checklist','Compliance Checklist'),
  i('compliance-overview','Compliance Overview'),
  i('compliance-packs','Compliance Packs'),
  i('compose-broadcast','Compose Broadcast'),
  i('content-safety','Content Safety'),
  i('core-competencies','Core Competencies'),
  i('creatives','Creatives'),
  i('custom-fields','Custom Fields'),
  i('dashboard','Dashboard'),
  i('data-records','Data Records'),
  i('data-validator','Data Validator'),
  i('datesheet','Datesheet'),
  i('departments','Departments'),
  i('design-settings','Design & Settings'),
  i('designations','Designations'),
  i('document-vault','Document Vault'),
  h('documents','DOCUMENTS'),
  i('drivers','Drivers'),
  i('due-slip-history','Due Slip History'),
  g('engagement','Engagement'),
  i('enter-marks','Enter Marks'),
  i('events-holidays','Events & Holidays'),
  i('exam-dashboard','Exam Dashboard'),
  g('exam-setup','Exam Setup'),
  i('exam-types','Exam Types'),
  h('exams','EXAMS'),
  i('expense','Expense'),
  i('expense-heads','Expense Heads'),
  i('face-monitoring','Face Monitoring'),
  i('facilities','Facilities'),
  i('fee-challans','Fee Challans'),
  i('fee-data-audit','Fee Data Audit'),
  i('fee-groups','Fee Groups'),
  i('fee-types','Fee Types'),
  i('feedback-triage','Feedback Triage'),
  h('fees','FEES'),
  i('fees-carry-forward','Fees Carry Forward'),
  i('fees-dashboard','Fees Dashboard'),
  i('fees-discount','Fees Discount'),
  g('fees-management','Fees Management'),
  g('fees-setup','Fees Setup'),
  i('festival-greetings','Festival Greetings'),
  i('field-settings','Field Settings'),
  g('finance-fees','Finance & Fees'),
  g('front-office','Front Office'),
  i('front-office-dashboard','Front Office Dashboard'),
  i('gate-passes','Gate Passes'),
  i('gate-terminal','Gate Terminal'),
  i('generate-due-slip','Generate Due Slip'),
  i('generate-marksheet','Generate Marksheet'),
  i('goods-receipts','Goods Receipts'),
  i('government-reports','Government Reports'),
  i('health-records','Health Records'),
  g('help-center','Help Center'),
  i('hero-slides','Hero Slides'),
  g('holistic-progress-card','Holistic Progress Card'),
  i('homework-assignments','Homework & Assignments'),
  g('hostel','Hostel'),
  i('hostel-dashboard','Hostel Dashboard'),
  i('hpc-activities','HPC Activities'),
  i('hpc-dashboard','HPC Dashboard'),
  i('hpc-frameworks','HPC Frameworks'),
  i('hr-dashboard','HR Dashboard'),
  i('hr-settings','HR Settings'),
  g('human-resource','Human Resource'),
  g('id-cards','ID Cards'),
  i('image-gallery','Image Gallery'),
  i('import-center','Import Center'),
  i('income','Income'),
  i('income-heads','Income Heads'),
  i('inspections','Inspections'),
  g('inventory','Inventory'),
  i('inventory-dashboard','Inventory Dashboard'),
  i('issue-item','Issue Item'),
  i('issue-return-book','Issue/Return Book'),
  i('item-categories','Item Categories'),
  i('item-list','Item List'),
  i('lead-dashboard','Lead Dashboard'),
  g('lead-management','Lead Management'),
  i('lead-pipeline-board','Lead Pipeline Board'),
  i('lead-sources-stages','Lead Sources & Stages'),
  g('leave-management','Leave Management'),
  i('leave-types','Leave Types'),
  i('lesson-plan-approvals','Lesson Plan Approvals'),
  i('lesson-plan-coverage','Lesson Plan Coverage'),
  i('lesson-plan-reports','Lesson Plan Reports'),
  i('lesson-plan-review','Lesson Plan Review'),
  g('lesson-planner','Lesson Planner'),
  i('lesson-planner-dashboard','Lesson Planner Dashboard'),
  i('lesson-planner-guide','Lesson Planner Guide'),
  i('lesson-planner-settings','Lesson Planner Settings'),
  i('lesson-plans','Lesson Plans'),
  g('library','Library'),
  i('library-dashboard','Library Dashboard'),
  i('live-class-settings','Live Class Settings'),
  g('live-classes','Live Classes'),
  i('live-operations','Live Operations'),
  i('live-vehicle-tracking','Live Vehicle Tracking'),
  i('manage-books','Manage Books'),
  i('manage-categories','Manage Categories'),
  i('manage-grades','Manage Grades'),
  i('manage-hostels','Manage Hostels'),
  i('manage-live-classes','Manage Live Classes'),
  i('manage-offline-exams','Manage Offline Exams'),
  i('manage-online-exams','Manage Online Exams'),
  i('manage-periods','Manage Periods'),
  i('manage-resources','Manage Resources'),
  i('manage-rooms','Manage Rooms'),
  i('manage-routes','Manage Routes'),
  i('manage-staff-loans','Manage Staff Loans'),
  i('manage-syllabus','Manage Syllabus'),
  i('manage-uploads','Manage Uploads'),
  i('manage-vehicles','Manage Vehicles'),
  h('management','MANAGEMENT'),
  g('marksheet-generation','Marksheet Generation'),
  i('messages','Messages'),
  i('module-settings','Module Settings'),
  h('modules','MODULES'),
  i('my-surveys','My Surveys'),
  i('my-timetable','My Timetable'),
  i('navigation-menu','Navigation Menu'),
  i('notice-board','Notice Board'),
  i('notification-settings','Notification Settings'),
  g('offline-examinations','Offline Examinations'),
  i('online-exam-dashboard','Online Exam Dashboard'),
  g('online-examinations','Online Examinations'),
  h('online-exams','ONLINE EXAMS'),
  i('online-transactions','Online Transactions'),
  i('osm-dashboard','OSM Dashboard'),
  i('osm-evaluate','OSM Evaluate'),
  i('osm-guide','OSM Guide'),
  i('osm-moderation','OSM Moderation'),
  g('osm-module','OSM Module'),
  i('osm-reports','OSM Reports'),
  i('osm-sessions','OSM Sessions'),
  i('pages','Pages'),
  i('parents-guardians','Parents & Guardians'),
  i('pathways-tracks','Pathways & Tracks'),
  i('payment-gateway','Payment Gateway'),
  i('payroll','Payroll'),
  i('point-of-sale','Point of Sale'),
  i('postal-records','Postal Records'),
  i('progress-cards','Progress Cards'),
  i('promote-students','Promote Students'),
  i('ptm-attendance-remarks','PTM Attendance & Remarks'),
  i('ptm-dashboard','PTM Dashboard'),
  i('ptm-follow-ups','PTM Follow-ups'),
  i('ptm-guide','PTM Guide'),
  g('ptm-meetings','PTM Meetings'),
  i('ptm-reports','PTM Reports'),
  i('ptm-schedule-meetings','PTM Schedule Meetings'),
  i('purchase-orders','Purchase Orders'),
  i('qr-attendance','QR Attendance'),
  i('qr-attendance-report','QR Attendance Report'),
  i('qr-attendance-setting','QR Attendance Setting'),
  g('qr-code-attendance','QR Code Attendance'),
  i('qr-scan-audit','QR Scan Audit'),
  i('question-bank','Question Bank'),
  i('report-card-setups','Report Card Setups'),
  i('reports-analytics','Reports & Analytics'),
  i('roles-permissions','Roles & Permissions'),
  i('room-types','Room Types'),
  i('salary-templates','Salary Templates'),
  i('sales-history','Sales History'),
  i('schedule-marks-setup','Schedule & Marks Setup'),
  i('school-profile','School Profile'),
  i('school-settings','School Settings'),
  g('school-website','School Website'),
  i('search-by-photo','Search by Photo'),
  i('search-due-fees','Search Due Fees'),
  i('sections','Sections'),
  i('set-salary','Set Salary'),
  g('settings-billing','Settings & Billing'),
  i('staff-attendance','Staff Attendance'),
  i('staff-attendance-report','Staff Attendance Report'),
  i('staff-directory','Staff Directory'),
  i('staff-id-card','Staff ID Card'),
  i('staff-id-cards','Staff ID Cards'),
  i('strands-outcomes','Strands & Outcomes'),
  i('student-admission','Student Admission'),
  i('student-allocation','Student Allocation'),
  i('student-attendance','Student Attendance'),
  i('student-attendance-report','Student Attendance Report'),
  i('student-categories','Student Categories'),
  i('student-dashboard','Student Dashboard'),
  i('student-houses','Student Houses'),
  i('student-id-cards','Student ID Cards'),
  g('student-information','Student Information'),
  i('student-list','Student List'),
  h('students','STUDENTS'),
  g('study-center','Study Center'),
  h('study-management','STUDY MANAGEMENT'),
  i('subjects','Subjects'),
  i('subscription','Subscription'),
  i('subscription-history','Subscription History'),
  i('supplier-payments','Supplier Payments'),
  i('suppliers','Suppliers'),
  i('survey-dashboard','Survey Dashboard'),
  i('survey-guide','Survey Guide'),
  g('surveys-feedback','Surveys & Feedback'),
  h('system','SYSTEM'),
  i('tc-exit','TC & Exit'),
  i('teacher-remarks','Teacher Remarks'),
  i('testimonials','Testimonials'),
  g('transport','Transport'),
  i('transport-dashboard','Transport Dashboard'),
  i('upload-marksheet','Upload Marksheet'),
  g('uploaded-marksheets','Uploaded Marksheets'),
  i('visitor-book','Visitor Book'),
  i('website-full-html','Website (Full HTML)'),
  i('website-overview','Website Overview'),
  i('website-templates','Website Templates'),
];
